name: Build & Test
description: Builds and runs tests on a .NET codebase

inputs:
  report-folder:
    description: Folder where report files will be generated
    required: false
    default: report

runs:
  using: "composite"
  steps:
    - name: Build .NET code
      run: dotnet build --no-restore --configuration Debug
      shell: bash
    - name: Run tests
      run: |
        dotnet test --no-build --verbosity normal --configuration Debug \
          --results-directory "${{ inputs.report-folder }}/TestResults" \
          --report-xunit-trx \
          --coverage --coverage-output-format cobertura
      shell: bash
      env:
        ASPNETCORE_ENVIRONMENT: Development
    - name: Generate test report
      if: hashFiles(format('{0}/TestResults/**/*.cobertura.xml', inputs.report-folder)) != ''
      run: |
        reportgenerator "-reports:${{ inputs.report-folder }}/TestResults/*.cobertura.xml" \
          "-targetdir:${{ inputs.report-folder }}" \
          "-reporttypes:Cobertura;Html;TextSummary;SonarQube"
      shell: bash
