name: Build and push a container image
description: Builds a new container image with Docker and pushes it to a registry

inputs:
  container_registry:
    description: Container registry
    required: true
  container_registry_username:
    description: Container registry username
    required: true
  container_registry_password:
    description: Container registry password
    required: true
  docker_file:
    description: Path to the Dockerfile
    required: true
  image_path:
    description: Image tag
    required: true
  image_name:
    description: Image name
    required: true
  image_tag:
    description: Image tag
    required: true
  create_latest:
    description: Create latest tag?
    required: false
    default: 'false'
  build_arguments:
    description: Container build arguments
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Login to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.container_registry }}
        username: ${{ inputs.container_registry_username }}
        password: ${{ inputs.container_registry_password }}

    - name: Build container image
      run: docker build . --file ${{ inputs.docker_file }} --tag ${{ inputs.image_path }}/${{ inputs.image_name }}:${{ inputs.image_tag }}${{ inputs.build_arguments }}
      shell: bash

    - name: Generate SBOM with Syft
      uses: anchore/sbom-action@v0
      continue-on-error: true
      with:
        image: ${{ inputs.image_path }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
        # format: spdx-json # Or cyclonedx-json
        # output-file: sbom.json
        # upload-artifact: true # Auto-upload to workflow artifacts

    - name: Push image to container registry
      run: docker push ${{ inputs.image_path }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
      shell: bash

    - name: Push latest tag to container registry
      if: ${{ inputs.create_latest == 'true' }}
      run: |
        docker tag ${{ inputs.image_path }}/${{ inputs.image_name }}:${{ inputs.image_tag }} ${{ inputs.image_path }}/${{ inputs.image_name }}:latest
        docker push ${{ inputs.image_path }}/${{ inputs.image_name }}:latest
      shell: bash

    - name: Install Cosign
      uses: sigstore/cosign-installer@v4.0.0
      with:
        cosign-release: 'v3.0.3'

    - name: Get image digest
      id: digest
      run: |
        DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ inputs.image_path }}/${{ inputs.image_name }}:${{ inputs.image_tag }} | cut -d'@' -f2)
        echo "DIGEST=$DIGEST" >> $GITHUB_OUTPUT
      shell: bash

    - name: Sign image with Cosign
      env:
        COSIGN_EXPERIMENTAL: 1
      run: |
        cosign sign --yes ${{ inputs.image_path }}/${{ inputs.image_name }}@${{ steps.digest.outputs.DIGEST }}
      shell: bash
