name: Build, Test & Analyze
description: Builds, runs tests on a .NET codebase and run analysis with Sonar

inputs:
  dotnet-test-args:
    description: .NET test arguments
    required: false
    default: ""
  java-version:
    description: Java version that will be installed (for Sonar CLI)
    required: false
    default: "21"
  sonar-exclusions:
    description: Files or directories that should be excluded from Sonar analysis
    required: false
    default: "node_modules"
  report-folder:
    description: Folder where report files will be generated
    required: false
    default: report
  sonar-host-url:
    description: Sonar host URL
    required: false
    default: ""
  sonar-organization:
    description: Sonar organization
    required: false
    default: ""
  sonar-project-key:
    description: Sonar project key
    required: false
    default: ""
  sonar-project-name:
    description: Sonar project name
    required: false
    default: ""
  sonar-token:
    description: Sonar token for login
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set up JDK for Sonar
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: "zulu"
    - name: Cache Sonar packages
      uses: actions/cache@v4
      with:
        path: ~/sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Sonar scanner
      id: cache-sonar-scanner
      uses: actions/cache@v4
      with:
        path: ./.sonar/scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner
    - name: Install Sonar scanner
      if: ${{ steps.cache-sonar-scanner.outputs.cache-hit != 'true' }}
      run: |
        mkdir -p ./.sonar/scanner
        dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
      shell: bash
    - name: Start code analysis
      run: |
        ./.sonar/scanner/dotnet-sonarscanner begin \
          /k:"${{ inputs.sonar-project-key }}" \
          /o:"${{ inputs.sonar-organization }}" \
          /n:"${{ inputs.sonar-project-name }}" \
          /d:sonar.token="${{ inputs.sonar-token}}" \
          /d:sonar.host.url="${{ inputs.sonar-host-url }}" \
          /d:sonar.cpd.exclusions="**/*Generated*.cs,${{ inputs.report-folder }}/**" \
          /d:sonar.exclusions="${{ inputs.report-folder }}/**,${{ inputs.sonar-exclusions }}" \
          /d:sonar.coverageReportPaths="${{ inputs.report-folder }}/SonarQube.xml" \
          /d:sonar.cs.vstest.reportsPaths="${{ inputs.report-folder }}/TestResults/*.trx"
      shell: bash
    - name: Build .NET solution
      run: dotnet build --no-restore --configuration Debug
      shell: bash
      env:
        BUILD_SOURCEBRANCHNAME: ${{ github.ref_name }}
        BUILD_BUILDID: ${{ github.run_id }}
    - name: Run tests
      run: |
        dotnet test --no-build --verbosity normal --configuration Debug \
          --results-directory "${{ inputs.report-folder }}/TestResults" \
          ${{ inputs.dotnet-test-args }}
      shell: bash
      env:
        ASPNETCORE_ENVIRONMENT: Development
    - name: Generate test report
      if: ${{ always() && hashFiles(format('{0}/TestResults/*.cobertura.xml', inputs.report-folder)) != '' }}
      run: |
        reportgenerator "-reports:${{ inputs.report-folder }}/TestResults/*.cobertura.xml" \
          "-targetdir:${{ inputs.report-folder }}" \
          "-reporttypes:Cobertura;Html;TextSummary;SonarQube"
      shell: bash
    - name: Complete code analysis
      run: ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{ inputs.sonar-token }}"
      shell: bash
