name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

env:
  python_version: "3.13"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out the repository
        uses: actions/checkout@v4
      - name: Lints Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: '**/*.md'
      - name: Set up Python ${{ env.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_version }}
      - name: Installs Python packages
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
      - name: Lint YAML files
        run: |
          yamllint .
