name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  markup-lint:
    name: Markup
    uses: ./.github/workflows/reusable-markup-lint.yml
