name: Reusable - Markup Lint

on:
  workflow_call:
    inputs:
      job-name:
        description: "Job name"
        type: string
        required: false
        default: "Lint"
      operating-system:
        description: "Operating system executing the runner"
        type: string
        required: false
        default: "ubuntu-latest"
      working-directory:
        description: "Working directory"
        type: string
        required: false
        default: "."

jobs:
  markup-lint:
    name: ${{ inputs.job-name }}
    runs-on: ${{ inputs.operating-system }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Lint Markdown files
        run: npx markdownlint-cli2 "**/*.md"
      - name: Lint YAML files
        run: pipx run yamllint .
